### ISSUE TITLE
Add Support for Package Qty

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#351]
**Is your feature request related to a problem? Please describe.**
Currently, having large multi-piece shipments with karrio is tedious to enter. Imagine a shipment of 20 boxes 10kg each with the same contents.

**Describe the solution you'd like**
We would like to specify a qty field for quickly adding identical packages to a shipments.

**Describe alternatives you've considered**
None.

**Additional context**
Getting and comparing rates for a 300 kg shipment with a max. weight of e.g. 30kg per parcel currently requires adding 10 packages to the rate request instead of one package item with qty 10.

**Comment by danh91** [comment]
I don't think it fit with the general API design. It will add complexity. IMO x number of packages should be defined separately as per the API even if they are identical.

It looks more like a convenience that the user interface can accommodate with shortcuts that multiply and sync copies of a package.

Even in the multi-piece shipment, after a label is created, each package gets a specific tracking number and unique references. Querying the database later on to get insight will also become complex because one package object will suddenly represent many by virtue of its quantity.

I am not sure this is the right approach for solving the problem.

Needs more observations 🤔

**Comment by MarcoWel** [comment]
If you add a qty field to the dashboard that creates x copies for the API would be a perfect solution for this issue already.
So you are right, this issue should be moved to the karrio dashboard.

**Comment by MarcoWel** [comment]
Moving this over to the dashboard issues.
