### ISSUE TITLE
[ DHL Express ] - Reps reject requests for API keys. Requires Certification

### ISSUE THREAD

**Issue by ggiraudon** [karrioapi/karrio#375]
Trying to get the credentials necessary for DHL Express to work in Karrio, we hit a bit of a snag.
DHL basically says that they will only issue API keys for use with existing certified vendors and that Karrio is not one of them.
See the following email from DHL : 
![DHL-Refusal](https://github.com/karrioapi/karrio/assets/326556/b0b15445-11eb-41f2-8ede-3de34dd56132)

**Comment by danh91** [comment]
Hi @ggiraudon ,

The email is correct indeed. while we have been through many certifications with some of our customers and early adopters,
we haven't registered Karrio itself as an official vendor/integrator with DHL (We tried the process with FedEx and UPS).

It is definitely something we wanted to do for a while but held off because our open-source nature is very uncommon for carriers right now. Every customer and early adopter we have helped get production credentials described Karrio as their own in-house built-in solution. 

This is what you can do right now tell them that you have your own API integration that you want to use in production because karrio isn't officially recognized by carriers as a registered vendor/integrator.  

This is part of what we are hoping to solve though. Fast-track this process so that people can deploy karrio and skip the certifications processes by virtue of mentioning their use of karrio.
Unfortunately, we are not there yet.

Thank you for opening this issue, I am going to close it and open a new one consisting of opening an application with DHL to get us recognized as vendor/integrator.
