### ISSUE TITLE
UPS OAUTH2 API Support - Current API being deprecated?

### ISSUE THREAD

**Issue by mazzarito** [karrioapi/karrio#565]
UPS will be deprecating the whole access key paradigm in a matter of months- does Karrio support the OAUTH2 version of this API or have plans to support it...? I setup a test and it doesn't seem to currently or am I missing something? Thanks! Looks like a great tool overall and I can tell a lot of good work has gone into it. Hopeful we can use it to transition away from our current custom integration rather than writing a new one to support OAUTH2.

**Comment by danh91** [comment]
Hi @mazzarito,
The upgrade to the latest UPS REST API was done long ago. 
What version of Karrio did you install?

**Comment by danh91** [comment]
Hi @mazzarito ,
I hope you noticed that the UPS connection accepts the `client_id` and `client_secret` used by Karrio to handle Oauth2 authentication.

Feel free to reopen this if you the issue is unresolved.

<img width="670" alt="Screenshot 2024-05-23 at 8 35 49 PM" src="https://github.com/karrioapi/karrio/assets/10974180/78d00730-6930-46c9-bdea-8a0dcf7b7a2b">
